server:
  port: ${SERVER_PORT:8084}

spring:
  profiles:
    default: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.myadminjavaeight.domain.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  access-token-expiration: 900000      # 15 分钟
  refresh-token-expiration: 604800000  # 7 天
  token-prefix: "Bearer "
  header: Authorization